# Redis Component
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskhub-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskhub-redis
  template:
    metadata:
      labels:
        app: taskhub-redis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: taskhub-redis
spec:
  selector:
    app: taskhub-redis
  ports:
  - port: 6379
    targetPort: 6379
