# complex-app/post-sync-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
  namespace: complex-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: post-sync
        image: alpine:3.14
        command: ["sh", "-c", "echo 'Running post-sync tasks' && sleep 5"]
      restartPolicy: Never
  backoffLimit: 1