[tools]
python = "3.12"
usage = "latest"

[env]
_.python.venv = { path = ".venv", create = true }
PROJECT_NAME = "taskhub-backend"
PREFIX = "{{ env.PROJECT_NAME }}"

[tasks."uv:reqs"]
description = "Install dependencies from requirements file"
alias = "uvr"
run = "uv pip install -r requirements.txt"

[tasks."uv:freeze"]
description = "Create requirements.txt from currently installed modules"
alias = "uvf"
run = "uv pip freeze > requirements.txt"

[tasks."uv:install"]
description = "Install pip packages"
alias = "uvi"
run = "uv pip install"

[tasks.install-deps]
description = "Install all dependencies"
run = "uv pip install fastapi uvicorn sqlalchemy psycopg2-binary redis pydantic python-dotenv"
alias = "deps"

[tasks.create-reqs]
description = "Create requirements.txt file"
run = "uv pip freeze > requirements.txt"

[tasks.dev]
description = "Run development server"
run = "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

[tasks.info]
description = "Print project information"
run = '''
echo "Project: "
echo "Virtual Environment: "
'''
