apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.0
        ports:
        - containerPort: 80